module.exports = {
  // USSD Response Types
  USSD_CONTINUE: 'CON',
  USSD_END: 'END',

  // Session States
  STATE_LANGUAGE_SELECTION: 'LANGUAGE_SELECTION',
  STATE_MAIN_MENU: 'MAIN_MENU',
  STATE_SUB_MENU_ACK: 'SUB_MENU_ACK',
  STATE_FARMER_REG_NAME: 'FARMER_REG_NAME',
  STATE_FARMER_REG_PROVINCE: 'FARMER_REG_PROVINCE',
  STATE_FARMER_REG_DISTRICT: 'FARMER_REG_DISTRICT',
  STATE_FARMER_REG_SECTOR: 'FARMER_REG_SECTOR',
  STATE_FARMER_REG_CELL: 'FARMER_REG_CELL',
  STATE_FARMER_REG_COMPLETE: 'FARMER_REG_COMPLETE', // Not strictly a state, but marks completion
  STATE_FARMER_UPDATE_MENU: 'FARMER_UPDATE_MENU', // For updating details

  // Main Menu Options
  MENU_OPTION_REGISTER_FARMER: '1', 
  MENU_OPTION_REQUEST_SERVICE: '2',
  MENU_OPTION_MY_REQUEST_STATUS: '3',
  MENU_OPTION_CHANGE_LANGUAGE: '4',
  MENU_OPTION_EXIT: '5',
  // New option for registered farmers
  MENU_OPTION_UPDATE_DETAILS: '1', 

  // Language Options
  LANG_EN_OPTION: '1',
  LANG_RW_OPTION: '2',
  LANG_SW_OPTION: '3',

  // Language Codes
  LANG_EN_CODE: 'en',
  LANG_RW_CODE: 'rw',
  LANG_SW_CODE: 'sw',

  // Navigation Options
  NAV_BACK_TO_MAIN_MENU: '0',
  NAV_BACK_TO_PREVIOUS: '00', 

  // Other constants
  MAX_NAME_LENGTH: 50,
};